# Project Configuration
project:
  name: "cv-defect-detection"
  version: "1.0.0"

# Data Configuration
data:
  raw_data_path: "data/raw"
  processed_data_path: "data/processed"
  train_split: 0.8
  val_split: 0.2

# Model Configuration
model:
  architecture: "yolov8n"
  pretrained: true
  num_classes: 6
  input_size: 640
  confidence_threshold: 0.25
  iou_threshold: 0.45

# Training Configuration
training:
  epochs: 50
  batch_size: 16
  learning_rate: 0.001
  device: "cpu"

# API Configuration
api:
  host: "0.0.0.0"
  port: 8000
  max_file_size_mb: 10